/**
 * Build info generator — runs at build time to populate
 * `src/lib/corefiles/build-info.ts` with real git metadata.
 *
 * Usage: `bun run scripts/generate-build-info.ts` (called by CI/CD)
 *
 * Copyright (c) 2026 Hasanur Jaya Sdn. Bhd.
 * Developer: amdsaib96
 */
import { execSync } from 'child_process'
import { writeFileSync } from 'fs'
import { resolve } from 'path'

function run(cmd: string, fallback = ''): string {
  try {
    return execSync(cmd, { encoding: 'utf-8' }).trim()
  } catch {
    return fallback
  }
}

const gitCommit = run('git rev-parse --short HEAD', 'unknown')
const gitBranch = run('git rev-parse --abbrev-ref HEAD', 'main')
const buildTime = new Date().toISOString()
const buildId = `build-${buildTime.slice(0, 10).replace(/-/g, '')}-${gitCommit}`
const version = run('node -p "require(\'./package.json\').version"', '1.0.0')

const content = `/**
 * Central build & ownership metadata for CoreFiles.
 *
 * AUTO-GENERATED by scripts/generate-build-info.ts — DO NOT EDIT MANUALLY.
 * Regenerated on every build via CI/CD.
 *
 * Copyright (c) 2026 Hasanur Jaya Sdn. Bhd.
 * CoreFiles Enterprise Document Management System
 * Developer: amdsaib96
 * All Rights Reserved.
 */

export interface BuildInfo {
  version: string
  buildId: string
  buildTime: string
  gitCommit: string
  gitBranch: string
  developer: string
  appName: string
  company: string
  copyright: string
  license: string
  homepage: string
  repository: string
}

export const BUILD_INFO: BuildInfo = {
  version: ${JSON.stringify(version)},
  buildId: ${JSON.stringify(buildId)},
  buildTime: ${JSON.stringify(buildTime)},
  gitCommit: ${JSON.stringify(gitCommit)},
  gitBranch: ${JSON.stringify(gitBranch)},
  developer: 'amdsaib96',
  appName: 'CoreFiles',
  company: 'Hasanur Jaya Sdn. Bhd.',
  copyright: 'Copyright (c) ${new Date().getFullYear()} Hasanur Jaya Sdn. Bhd.',
  license: 'Proprietary — All Rights Reserved',
  homepage: 'https://corefiles.hasanurjaya.com',
  repository: 'https://github.com/hsphotographyhasib-design/corefiles',
}

export const ATTRIBUTION = \`© ${new Date().getFullYear()} Hasanur Jaya Sdn. Bhd. · Developed by \${BUILD_INFO.developer}\`

export const STARTUP_BANNER = \`
======================================
  \${BUILD_INFO.appName} Enterprise
  Version \${BUILD_INFO.version}
  Build \${BUILD_INFO.buildId}
  Developer: \${BUILD_INFO.developer}
  \${BUILD_INFO.copyright}
======================================
\`.trim()
`

writeFileSync(resolve(process.cwd(), 'src/lib/corefiles/build-info.ts'), content)
console.log(`[build-info] Generated: ${buildId} (commit ${gitCommit}, branch ${gitBranch})`)
